name: 'Kustomize Edit'
description: 'Edit kustomize overlays - set images, labels, annotations, and apply patches'
author: 'KoalaOps'

branding:
  icon: 'edit'
  color: 'purple'

inputs:
  overlay_dir:
    description: 'Path to kustomize overlay directory'
    required: true
  image:
    description: 'Image name (without tag)'
    required: false
  tag:
    description: 'Image tag'
    required: false
  version_label:
    description: 'Value for app.kubernetes.io/version label'
    required: false
  annotations:
    description: 'Annotations to add (key=value format, one per line)'
    required: false
  labels:
    description: 'Labels to add (key=value format, one per line)'
    required: false
  name_prefix:
    description: 'Name prefix to set'
    required: false
  name_suffix:
    description: 'Name suffix to set'
    required: false
  namespace:
    description: 'Namespace to set'
    required: false
  replicas:
    description: 'Replicas count to set (JSON format, e.g., [{"name":"deployment-name","count":3}])'
    required: false
  json_patches:
    description: 'JSON6902 patches to apply (JSON array)'
    required: false

outputs:
  overlay_dir:
    description: 'Path to the edited overlay'
    value: ${{ inputs.overlay_dir }}
  kustomization_file:
    description: 'Path to kustomization.yaml'
    value: ${{ inputs.overlay_dir }}/kustomization.yaml

runs:
  using: 'composite'
  steps:
    - name: Validate overlay directory
      shell: bash
      run: |
        set -euo pipefail
        if [ ! -d "${{ inputs.overlay_dir }}" ]; then
          echo "::error::Overlay directory not found: ${{ inputs.overlay_dir }}"
          exit 1
        fi
        
        if [ ! -f "${{ inputs.overlay_dir }}/kustomization.yaml" ]; then
          echo "::error::No kustomization.yaml found in ${{ inputs.overlay_dir }}"
          exit 1
        fi
        
        echo "âœ… Found kustomization.yaml in: ${{ inputs.overlay_dir }}"
    
    - name: Set image and tag
      if: inputs.image != '' && inputs.tag != ''
      shell: bash
      working-directory: ${{ inputs.overlay_dir }}
      run: |
        set -euo pipefail
        echo "ðŸ·ï¸ Setting image: ${{ inputs.image }}:${{ inputs.tag }}"
        # Try to set image - kustomize will handle both new and existing images
        kustomize edit set image "${{ inputs.image }}=${{ inputs.image }}:${{ inputs.tag }}"
    
    - name: Set version label
      if: inputs.version_label != ''
      shell: bash
      working-directory: ${{ inputs.overlay_dir }}
      run: |
        set -euo pipefail
        echo "ðŸ·ï¸ Setting version label: ${{ inputs.version_label }}"
        # kustomize edit add label will update if exists or add if not
        kustomize edit add label "app.kubernetes.io/version:${{ inputs.version_label }}"
    
    - name: Add annotations
      if: inputs.annotations != ''
      shell: bash
      working-directory: ${{ inputs.overlay_dir }}
      run: |
        set -euo pipefail
        echo "ðŸ“ Adding annotations..."
        echo "${{ inputs.annotations }}" | while IFS= read -r annotation; do
          if [ -n "$annotation" ]; then
            echo "  - $annotation"
            kustomize edit add annotation "$annotation"
          fi
        done
    
    - name: Add labels
      if: inputs.labels != ''
      shell: bash
      working-directory: ${{ inputs.overlay_dir }}
      run: |
        set -euo pipefail
        echo "ðŸ·ï¸ Adding labels..."
        echo "${{ inputs.labels }}" | while IFS= read -r label; do
          if [ -n "$label" ]; then
            echo "  - $label"
            kustomize edit add label "$label"
          fi
        done
    
    - name: Set name prefix
      if: inputs.name_prefix != ''
      shell: bash
      working-directory: ${{ inputs.overlay_dir }}
      run: |
        set -euo pipefail
        echo "ðŸ“› Setting name prefix: ${{ inputs.name_prefix }}"
        kustomize edit set nameprefix "${{ inputs.name_prefix }}"
    
    - name: Set name suffix
      if: inputs.name_suffix != ''
      shell: bash
      working-directory: ${{ inputs.overlay_dir }}
      run: |
        set -euo pipefail
        echo "ðŸ“› Setting name suffix: ${{ inputs.name_suffix }}"
        kustomize edit set namesuffix "${{ inputs.name_suffix }}"
    
    - name: Set namespace
      if: inputs.namespace != ''
      shell: bash
      working-directory: ${{ inputs.overlay_dir }}
      run: |
        set -euo pipefail
        echo "ðŸ“ Setting namespace: ${{ inputs.namespace }}"
        kustomize edit set namespace "${{ inputs.namespace }}"
    
    - name: Set replicas
      if: inputs.replicas != ''
      shell: bash
      working-directory: ${{ inputs.overlay_dir }}
      run: |
        set -euo pipefail
        echo "ðŸ”¢ Setting replicas..."
        REPLICAS='${{ inputs.replicas }}'
        
        # Validate JSON
        if ! echo "$REPLICAS" | jq empty 2>/dev/null; then
          echo "::error::Invalid replicas JSON format"
          exit 1
        fi
        
        # Process each replica setting
        echo "$REPLICAS" | jq -c '.[]' | while read -r replica; do
          NAME=$(echo "$replica" | jq -r '.name // empty')
          COUNT=$(echo "$replica" | jq -r '.count // empty')
          if [ -z "$NAME" ] || [ -z "$COUNT" ]; then
            echo "::error::replicas entries must have {\"name\",\"count\"}"
            exit 1
          fi
          echo "  - $NAME: $COUNT replicas"
          kustomize edit set replicas "${NAME}=${COUNT}"
        done
    
    - name: Apply JSON patches
      if: inputs.json_patches != ''
      shell: bash
      working-directory: ${{ inputs.overlay_dir }}
      run: |
        set -euo pipefail
        echo "ðŸ”§ Applying JSON patches..."
        PATCHES='${{ inputs.json_patches }}'
        
        # Validate JSON
        if ! echo "$PATCHES" | jq -e . >/dev/null 2>&1; then
          echo "::error::Invalid json_patches format"
          exit 1
        fi
        
        # Create patches directory
        mkdir -p patches
        
        # Build the patches section
        PATCHES_FILE=$(mktemp)
        HAS_PATCHES=false
        
        # Process each patch and create patch files
        i=0
        echo "$PATCHES" | jq -c '.[]' | while read -r patch; do
          i=$((i+1))
          PATCH_FILE="patches/patch-${i}.json"
          
          echo "$patch" > "$PATCH_FILE"
          echo "  - Created $PATCH_FILE"
          
          # Build the patch entry
          TARGET=$(echo "$patch" | jq -r '.target // empty')
          if [ -n "$TARGET" ]; then
            # Format with target
            {
              echo "- path: $PATCH_FILE"
              echo "  target:"
              echo "$TARGET" | jq -r 'to_entries[] | "    \(.key): \(.value)"'
            } >> "$PATCHES_FILE"
          else
            # Simple patch reference
            echo "- path: $PATCH_FILE" >> "$PATCHES_FILE"
          fi
          HAS_PATCHES=true
        done
        
        # Add patches to kustomization.yaml if we have any
        if [ -s "$PATCHES_FILE" ]; then
          # Check if patches section already exists
          if grep -q '^patches:' kustomization.yaml; then
            # Append to existing patches section
            sed -i '/^patches:/r '"$PATCHES_FILE" kustomization.yaml
          else
            # Add new patches section
            echo "" >> kustomization.yaml
            echo "patches:" >> kustomization.yaml
            cat "$PATCHES_FILE" >> kustomization.yaml
          fi
        fi
        
        rm -f "$PATCHES_FILE"
    
    - name: Validate kustomization
      shell: bash
      working-directory: ${{ inputs.overlay_dir }}
      run: |
        set -euo pipefail
        echo "âœ… Validating kustomization..."
        if ! kustomize build . > /dev/null 2>&1; then
          echo "::error::Kustomization validation failed"
          kustomize build . 2>&1 | head -20
          exit 1
        fi
        echo "âœ… Kustomization is valid"
        
        echo "ðŸ“‹ Final kustomization.yaml:"
        cat kustomization.yaml